[vps]
local_vm ansible_host=192.168.88.80 ansible_user=admin ansible_ssh_private_key_file=/home/bernd/.ssh/id_ed25519
yandex_cloud ansible_host=111.111.111.111 ansible_user=bernd ansible_ssh_private_key_file=/home/bernd/.ssh/yandex_cloud

[vps:vars]
ansible_python_interpreter=/usr/bin/python3
